
GET http://localhost:4000/api/accounts
###
POST http://localhost:4000/api/accounts
Content-Type: application/json

{
    
    "precio": 452121,
    "nombre": "ajksjlaksajlskas",
    "apellido": "producto",
    "cuenta": 1235546,
    "banco": "bod",
    "documento": "J",
    "CI": 456656,
    "img": "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "done": true
}

###
GET http://localhost:4000/api/accounts/60904c5c69f9120f184bc174

###
DELETE http://localhost:4000/api/accounts/60904be369f9120f184bc173

###
GET http://localhost:4000/api/accounts/done

###
PUT http://localhost:4000/api/accounts/60904be369f9120f184bc173
Content-Type: application/json

{
    
    "precio": 8000,
    "nombre": "testeo123",
    "apellido": "testeo2212",
    "cuenta": 1235451,
    "banco": "mercantil",
    "documento": "J",
    "CI": 456656,
    "img": "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "done": true
}

//CREAR ORDENES
